#!/bin/bash
set -xe 

echo "Installing dependencies.."
sudo yum install -q -y automake e2fsprogs-libs e2fsprogs-devel \
libblkid-devel zlib-devel lzo-devel asciidoc xmlto which \
findutils xz gcc make libtool attr libzstd libzstd-devel python3-devel
echo "Installing dependencies..done"

# Clone repo
git clone https://github.com/kdave/btrfs-progs.git -b devel

# Build
cd ~/btrfs-progs && ./autogen.sh && \
./configure --prefix /usr CFLAGS="-I/usr/include" LDFLAGS="-L/usr/lib"  \
&& make && sudo make install

echo "Kernel info:"
uname -a
# Run tests
cd ~/btrfs-progs && make test-fsck && make test-cli && make test-misc && make test-fuzz

#
if [ $? -eq 0 ];
then
touch ~/btrfsqe/002_btrfsprogs.completed
fi
