#!/bin/bash
set -xe 

#!/bin/bash
set -xe 
echo "Installing dependencies.."
sudo yum -q -y install acl attr automake bc dbench dump e2fsprogs fio gawk gcc indent libtool lvm2 make psmisc quota sed xfsdump xfsprogs libacl-devel libattr-devel libaio-devel libuuid-devel xfsprogs-devel 
echo "Installing dependencies..done"

# Clone repo
git clone https://github.com/kdave/xfstests.git
# Start the build
cd ~/xfstests && make && sudo make install

# Prepare env and setup local.config
sudo mkdir -p /mnt/test && sudo mkdir -p /mnt/scratch
sudo mkfs.btrfs /dev/xvdb
cp -v ~/btrfsqe/local.config ~/xfstests

# Run 011 with smaller file and counts
sed -i "s/fssize=2048/fssize=64/" ~/xfstests/tests/btrfs/011
sed -i "s/bs=1M/bs=512K/" ~/xfstests/tests/btrfs/011


echo "Kernel info:"
uname -a
# Run tests
cd ~/xfstests && sudo ./check "tests/btrfs/*"

#
if [ $? -eq 0 ];
then
touch ~/btrfsqe/003_xfstests.completed
fi
